// renderer/engine/events.js

export const EventTypes = {
  SESSION_CREATED: 'SESSION_CREATED',
  PARTICIPANT_JOIN_REQUESTED: 'PARTICIPANT_JOIN_REQUESTED',
  PARTICIPANT_APPROVED: 'PARTICIPANT_APPROVED',

  LOT_STARTED: 'LOT_STARTED',

  BID_ACCEPTED: 'BID_ACCEPTED',
  BID_REJECTED: 'BID_REJECTED',

  LOT_CLOSED: 'LOT_CLOSED',
  LOT_SOLD: 'LOT_SOLD',
  LOT_UNSOLD: 'LOT_UNSOLD',

  SESSION_CLOSED: 'SESSION_CLOSED'
}